version: '3.7'

services:
  client:
    build: .
    working_dir: /app
    volumes:
      - "./client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: .
    working_dir: /app
    volumes:
      - "./server:/app"
    ports:
      - "8888:8888"
